[package]
name = "trakt_raknet"
description = "Raknet Protocol partial implementation for use in trakt"
version = "1.0.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
log = "0.4.20"
anyhow = "1.0"
tokio = { version = "1.32", features = ["full"] }

bytes = "1.4"
ppp = "2.2"
